kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: nginx-namespace-12090
  uid: 9a4e1423-d1af-444e-b8a1-8e9ecd08ed19
  resourceVersion: '223224'
  creationTimestamp: '2024-12-06T11:25:32Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2024-12-06T11:25:32Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:internalTrafficPolicy': {}
          'f:ports':
            .: {}
            'k:{"port":80,"protocol":"TCP"}':
              .: {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector': {}
          'f:sessionAffinity': {}
          'f:type': {}
spec:
  clusterIP: 172.30.43.247
  ipFamilies:
    - IPv4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.30.43.247
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: MyApp
status:
  loadBalancer: {}
